### ISSUE TITLE
Adding a mute-unmute functionality for the game-bgm.

### ISSUE THREAD

**Issue by MrPhenomenal3110** [MrPhenomenal3110/Tic-Tac-Toe#3]
Add a functionality to mute or unmute the background music.

**Comment by Bolaji06** [comment]
Hello @MrPhenomenal3110 can I work on this issue?

**Comment by MrPhenomenal3110** [comment]
> Hello @MrPhenomenal3110 can I work on this issue?

Yeah Sure  !! Let me assign this to you !

**Comment by Bolaji06** [comment]
Thanks for letting me work on this project

**Comment by Bolaji06** [comment]
Have sent a PR kindly review. Hoping to hear a feedback from you.

**Comment by MrPhenomenal3110** [comment]
Everything else seems fine, but the music still plays on clicking the reset button even when the toggle state is off. Could you resolve this ?

**Comment by Bolaji06** [comment]
If I can get your requirements, you don't want the music to play when the reset button is clicked?

**Comment by Bolaji06** [comment]
> If I can get your requirements, you don't want the music to play when the reset button is clicked?

Or you want the music to play when the reset button is clicked, and it should only play when the toggle button is on.

**Comment by Bolaji06** [comment]
> > If I can get your requirements, you don't want the music to play when the reset button is clicked?
> 
> Or you want the music to play when the reset button is clicked, and it should only play when the toggle button is on.

Kindly help me to clarify what your requirements are, so that I can understand what your needs are. Thanks

**Comment by MrPhenomenal3110** [comment]
> > If I can get your requirements, you don't want the music to play when the reset button is clicked?
> 
> Or you want the music to play when the reset button is clicked, and it should only play when the toggle button is on.

I am so sorry I was unable to reply to you all this time ... Yes, this is the functionality that I was  asking for.
